export const produtos = [
  { nome: 'Nike Phantom', categoria: 'chuteiras nike', img: 'img/nike27.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Adidas Pure FG', categoria: 'chuteiras adidas', img: 'img/adida1.jpeg', preco: 'R$ 340,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Puma Future', categoria: 'chuteiras puma', img: 'img/puma1.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Adidas X Speed...', categoria: 'chuteiras adidas', img: 'img/adida7.jpeg', preco: 'R$ 310,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Mizuno Morela', categoria: 'chuteiras mizuno', img: 'img/mizuno1.jpeg', preco: 'R$ 310,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Puma Fut Utimate', categoria: 'chuteiras puma', img: 'img/puma5.jpeg', preco: 'R$ 340,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Nike Vapor', categoria: 'chuteiras nike', img: 'img/nike21.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Adidas Predator', categoria: 'chuteiras adidas', img: 'img/adida14.jpeg', preco: 'R$ 310,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Nike Phantom GT', categoria: 'chuteiras nike', img: 'img/nike11.jpeg', preco: 'R$ 35,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Adidas Speed FIT', categoria: 'chuteiras adidas', img: 'img/adida18.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Puma Future Z 1.3', categoria: 'chuteiras puma', img: 'img/puma10.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Puma Ultra', categoria: 'chuteiras puma', img: 'img/puma16.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Adidas adi Kroos', categoria: 'chuteiras adidas', img: 'img/adida21.jpeg', preco: 'R$ 330,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Nike Mercurial', categoria: 'chuteiras nike', img: 'img/nike17.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Nike Mercurial TF', categoria: 'chuteiras nike', img: 'img/nike8.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Nike Mercu Vapor', categoria: 'chuteiras nike', img: 'img/nike20a.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Adidas Predator', categoria: 'chuteiras adidas', img: 'img/adida30.jpeg', preco: 'R$ 330,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Adidas Crazyfast', categoria: 'chuteiras adidas', img: 'img/adida28.jpeg', preco: 'R$ 340,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Mizuno Morelia', categoria: 'chuteiras mizuno', img: 'img/mizuno9.jpeg', preco: 'R$ 320,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  { nome: 'Nike AIR Zoom', categoria: 'chuteiras nike', img: 'img/nike1.jpeg', preco: 'R$ 330,00', descricao: 'à vista <br> ou até 3x sem juros.' },
  
  { nome: 'Nike Phantom', categoria: 'chuteiras society', img: './img/nike100.jpeg', preco: 'R$ 320,00', descricao:'à vista <br> ou até 3x sem juros.'},
  { nome: 'Adidas F50', categoria: 'chuteiras society', img: './img/adidas2.jpeg', preco: 'R$ 340,00', descricao:'à vista <br> ou até 3x sem juros.'},
  { nome: 'Nike', categoria: 'chuteiras society', img: './img/nike210.jpeg', preco: 'R$ 310,00', descricao:'à vista <br> ou até 3x sem juros.'},
  { nome: 'Puma Fut Ultimate', categoria: 'chuteiras society', img: './img/puma101.jpeg', preco: 'R$ 340,00', descricao:'à vista <br> ou até 3x sem juros.'},
  { nome: 'Nike Tiempo', categoria: 'chuteiras society', img: './img/nike101.jpeg', preco: 'R$ 310,00', descricao:'à vista <br> ou até 3x sem juros.'},
  { nome: 'Mizuno Morela', categoria: 'chuteiras society', img: './img/mizuno55.jpeg', preco: 'R$ 330,00', descricao:'à vista <br> ou até 3x sem juros.'},
  { nome: 'Puma Future', categoria: 'chuteiras society', img: './img/puma100.jpeg', preco: 'R$ 320,00', descricao:'à vista <br> ou até 3x sem juros.'},
  { nome: 'Nike Air Zoom', categoria: 'chuteiras society', img: './img/nike250.jpeg', preco: 'R$ 320,00', descricao:'à vista <br> ou até 3x sem juros.'},

  { nome: 'Tenis Air Max Nike', categoria: 'tenis', img: './img/tenis-nike1.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Casual Nike', categoria: 'tenis1', img: './img/tenis-nike2.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Nike', categoria: 'tenis', img: './img/tenis-nike3.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Nike', categoria: 'tenis', img: './img/tenis-nike4.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Feminino', categoria: 'tenis', img: './img/tenis-nike5.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Adidas Classico', categoria: 'tenis', img: './img/tenis2.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Adidas', categoria: 'tenis', img: './img/tenis1.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Adidas', categoria: 'tenis', img: './img/tenis3.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Adidas', categoria: 'tenis', img: './img/tenis4.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Adidas', categoria: 'tenis', img: './img/tenis5.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Mizuno', categoria: 'tenis', img: './img/tenis-mizuno.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
  { nome: 'Tenis Puma', categoria: 'tenis', img: './img/tenis-puma.jpeg', preco: 'R$ 0,00', descricao:'Produto indisponivel no momento!'},
];